version: "3"

services:
  mypostgres:
    image: postgres:15.1-alpine
    ports:
      - "5432:5432"
    container_name: pg-container
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: Ken
      POSTGRES_DB: kensdb
    volumes:
      - /Users/Ken/workspace/docker/postgresData:/var/lib/postgresql/data

  mysanic:
    image: kens-sanic:latest
    ports:
      - "8000:8000"
    restart: always

  mynginx:
    image: nginx:1.13.6-alpine
    ports:
      - "80:80"
    depends_on:
      - mysanic
    volumes:
      - ./mysanic.conf:/etc/nginx/conf.d/mysanic.conf
    restart: always

networks:
  default:
    driver: bridge
 